title: Beginner App Inventor Sushi Cards
hero_image: images/banner.png
description: Learn how to use App Inventor to make a quiz app
theme: green # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2
listed: false
ingredient: false
copyedit: false
interests: animals, art, humour, space, photography, outdoors, music, games
technologies: electronic-components, sense-hat, html-css-javascript, scratch, python
site_areas: coderdojo
version: 1
last_tested: 2017-01-01
steps: 
  - title: Introduction
  - title: What you will need
  - title: Get set up
  - title: Create a question
  - title: Keep score
  - title: More questions
  - title: Finish your app
  - title: What next?
