---
title: Canine quiz
hero_image: images/banner.png
description: Learn how to use App Inventor to make a quiz app
theme: green
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 2, design-0, programming-2, phys-comp-0, manufacture-0, community-0
interests: animals
technologies: app-inventor
site_areas: coderdojo
hardware: 
software: app-inventor
version: 4.0.0
last_tested: 2017-01-01
steps:
- title: Introduction
- title: Get set up
- title: Create a question
  completion:
  - engaged
- title: Keep score
- title: More questions
- title: Finish your app
  completion:
  - internal
- title: What next?
